Use poshlib; bash boilerplate

diff --git a/bin/stash b/bin/stash
--- a/bin/stash
+++ b/bin/stash
@@ -1,5 +1,32 @@
 exec < $0
 
+# boilerplate
+
+set -euo pipefail
+err_report() {
+    echo "errexit on line $(caller)" >&2
+}
+trap err_report ERR
+
+die() {
+    echo $2 >&2
+    exit $1
+}
+
+SCRIPT_DIR=$(dirname $(readlink -f $0))
+
+[[ -f $SCRIPT_DIR/poshlib/parse-opt.sh ]] || die 1 "Could not find poshlib"
+# No short arguments
+declare -A PO_SHORT_MAP
+
+# All long arguments are lowercase versions of their corresponding envars
+# with the prefix STASH_ removed.
+declare -A PO_LONG_MAP
+PO_LONG_MAP["flags:"]="STASH_FLAGS"
+
+# parse command line options
+. $SCRIPT_DIR/poshlib/parse-opt.sh
+
 # init
 
 __STASH__dir=$(mktemp -d)
@@ -37,8 +64,8 @@ do
     #   if continuation, slurp in next line and loop (deleting newline)
     #   tokenise
     #   detect structure
-    # if opening structure, push structure stack
-    # elif closing structure, pop structure stack
+    # if opening structure, push structure stack and recurse
+    # elif closing structure, pop structure stack and return
     # write out
     echo "$__STASH__outline" >> $__STASH__dir/main
     # loop
